### ISSUE TITLE
Does not sync anymore

### ISSUE THREAD

**Issue by iSchorsch** [nicolindemann/coinbase-moneymoney#7]
For more than a week, the plug in does not sync anymore. Checked the API settings on the webSite of CoinBase. Everything seems to be correct - used to work before.

Error message:

Der API-Server Ihrer Bank antwortet mit der Fehlermeldung:
»Bad Request«

Bitte versuchen Sie es später noch einmal oder wenden Sie sich mit dieser Fehlermeldung an den Support Ihrer Bank.

**Comment by ncserny** [comment]
Same issue here. Please check.
<img width="503" alt="Screen Shot 2020-11-24 at 11 05 15" src="https://user-images.githubusercontent.com/5199712/100079630-2d25b880-2e45-11eb-9f59-d2c22a9f0dae.png">

**Comment by smnkrl** [comment]
Same issue here - it always fails at the same stage:


```
1> Sending: GET https://api.coinbase.com/v2/exchange-rates?currency=REPV2
1> HTTPS response: Bad Request
1> The server responded with the error message: Bad Request. Retrying...
1> Sending: GET https://api.coinbase.com/v2/exchange-rates?currency=REPV2
1> HTTPS response: Bad Request
1> Der API-Server Ihrer Bank antwortet mit der Fehlermeldung: »Bad Request«  Bitte versuchen Sie es später noch einmal oder wenden Sie sich mit dieser Fehlermeldung an den Support Ihrer Bank.
```

**Comment by jvgh1** [comment]
Same here:

`Sending: GET https://api.coinbase.com/v2/exchange-rates?currency=REPV2; HTTPS response: Bad Request`

**Comment by udochrist** [comment]
i have changed the code to remove the request for REPv2 as this is a not allowed contract to watch for me.
however my knowledge of lua coding as well as coinbase api is not to far adanced.
Besides i do not know how to generate the correct signature so this ext can be used w/o turning of sigs in the beta version....
if you want i can generate a PR

**Comment by iSchorsch** [comment]
Thank you very much for your effort! Did you try your modification and does it work? If it fetches your account correctly I would be very happy if you could share your extension, even if we would have to enable ß-support / non signed extensions.
I am curious if the original developer of this great Lua is still able to respond?

**Comment by udochrist** [comment]
> Thank you very much for your effort! Did you try your modification and does it work? If it fetches your account correctly I would be very happy if you could share your extension, even if we would have to enable ß-support / non signed extensions.
> I am curious if the original developer of this great Lua is still able to respond?

This is my quick fix. It simply skips over REPV2. 

https://github.com/udochrist/coinbase-moneymoney/blob/fixREPv2/src/Coinbase.lua

**Comment by iSchorsch** [comment]
Great! This does work now. Thank you! *thumbs up*

**Comment by fabge** [comment]
How were you able to add a extension without the right signature?
Were can I turn the checking for signature off?

**Comment by mr089** [comment]
> 
> This is my quick fix. It simply skips over REPV2.
> 
> https://github.com/udochrist/coinbase-moneymoney/blob/fixREPv2/src/Coinbase.lua


it works again. many thanks

**Comment by udochrist** [comment]
Update to the beta app and enable unsigned extensions. See the apps FAQ

**Comment by smnkrl** [comment]
MoneyMoney provided a new signed version of the extension - it works fine for me. 
https://moneymoney-app.com/extensions/

![20201130162339](https://user-images.githubusercontent.com/3878518/100628368-6e780580-3328-11eb-94a0-2224f101821d.png)

**Comment by iSchorsch** [comment]
super! Bei mir auch! DANKE!
